-- Marchés - Phase B : catalogue externe en lecture seule.
-- Migration additive et rejouable. Elle ne touche ni eclats_ledger ni les tables utilisateur.

begin;

create table if not exists public.mk_events (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('POLYMARKET', 'MANIFOLD')),
  external_id text not null,
  slug text,
  title text not null,
  description text,
  source_url text,
  image_url text,
  category text,
  regions text[] not null default array['Monde']::text[],
  status text not null check (status in ('OPEN', 'CLOSED', 'RESOLVED', 'CANCELLED')),
  close_at timestamptz,
  resolution_source text,
  volume numeric(24,8) not null default 0 check (volume >= 0),
  volume_24h numeric(24,8) not null default 0 check (volume_24h >= 0),
  liquidity numeric(24,8) not null default 0 check (liquidity >= 0),
  raw_payload jsonb not null default '{}'::jsonb,
  source_updated_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unavailable_at timestamptz,
  unique (source, external_id)
);

create table if not exists public.mk_markets (
  id bigint generated by default as identity primary key,
  event_id bigint references public.mk_events(id) on delete set null,
  source text not null check (source in ('POLYMARKET', 'MANIFOLD')),
  external_id text not null,
  slug text,
  title text not null,
  description text,
  source_url text not null,
  image_url text,
  market_type text not null,
  category text,
  regions text[] not null default array['Monde']::text[],
  status text not null check (status in ('OPEN', 'CLOSED', 'RESOLVED', 'CANCELLED')),
  tradable boolean not null default false,
  non_tradable_reason text,
  close_at timestamptz,
  expected_resolution_at timestamptz,
  resolution_source text,
  volume numeric(24,8) not null default 0 check (volume >= 0),
  volume_24h numeric(24,8) not null default 0 check (volume_24h >= 0),
  liquidity numeric(24,8) not null default 0 check (liquidity >= 0),
  bettor_count bigint check (bettor_count is null or bettor_count >= 0),
  spread numeric(12,10) check (spread is null or spread >= 0),
  raw_payload jsonb not null default '{}'::jsonb,
  source_updated_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unavailable_at timestamptz,
  unique (source, external_id)
);

create table if not exists public.mk_outcomes (
  id bigint generated by default as identity primary key,
  market_id bigint not null references public.mk_markets(id) on delete cascade,
  external_id text not null,
  label text not null,
  position integer not null default 0 check (position >= 0),
  probability numeric(12,10) check (probability is null or probability between 0 and 1),
  previous_24h numeric(12,10) check (previous_24h is null or previous_24h between 0 and 1),
  clob_token_id text,
  source_market_id text,
  condition_id text,
  raw_payload jsonb not null default '{}'::jsonb,
  last_seen_at timestamptz not null default now(),
  unique (market_id, external_id)
);

create table if not exists public.mk_price_snapshots (
  id bigint generated by default as identity primary key,
  outcome_id bigint not null references public.mk_outcomes(id) on delete cascade,
  probability numeric(12,10) not null check (probability between 0 and 1),
  best_bid numeric(12,10) check (best_bid is null or best_bid between 0 and 1),
  best_ask numeric(12,10) check (best_ask is null or best_ask between 0 and 1),
  source_timestamp timestamptz,
  recorded_at timestamptz not null default now()
);

create unique index if not exists mk_price_snapshots_outcome_bucket_uidx
  on public.mk_price_snapshots (outcome_id, recorded_at);

create table if not exists public.mk_sync_runs (
  id bigint generated by default as identity primary key,
  run_id uuid not null unique,
  trigger text not null default 'manual',
  started_at timestamptz not null,
  finished_at timestamptz,
  status text not null check (status in ('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED')),
  polymarket_count integer not null default 0 check (polymarket_count >= 0),
  manifold_count integer not null default 0 check (manifold_count >= 0),
  market_count integer not null default 0 check (market_count >= 0),
  outcome_count integer not null default 0 check (outcome_count >= 0),
  snapshot_count integer not null default 0 check (snapshot_count >= 0),
  error_summary jsonb not null default '[]'::jsonb
);

create index if not exists mk_events_status_close_idx
  on public.mk_events (status, close_at);
create index if not exists mk_markets_status_volume_idx
  on public.mk_markets (status, volume_24h desc);
create index if not exists mk_markets_category_idx
  on public.mk_markets (category);
create index if not exists mk_outcomes_market_position_idx
  on public.mk_outcomes (market_id, position);
create index if not exists mk_price_snapshots_outcome_time_idx
  on public.mk_price_snapshots (outcome_id, recorded_at desc);
create index if not exists mk_sync_runs_started_idx
  on public.mk_sync_runs (started_at desc);

alter table public.mk_events enable row level security;
alter table public.mk_markets enable row level security;
alter table public.mk_outcomes enable row level security;
alter table public.mk_price_snapshots enable row level security;
alter table public.mk_sync_runs enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'mk_events' and policyname = 'mk_events_read') then
    create policy mk_events_read on public.mk_events for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'mk_markets' and policyname = 'mk_markets_read') then
    create policy mk_markets_read on public.mk_markets for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'mk_outcomes' and policyname = 'mk_outcomes_read') then
    create policy mk_outcomes_read on public.mk_outcomes for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'mk_price_snapshots' and policyname = 'mk_price_snapshots_read') then
    create policy mk_price_snapshots_read on public.mk_price_snapshots for select using (true);
  end if;
end $$;

revoke insert, update, delete, truncate on
  public.mk_events, public.mk_markets, public.mk_outcomes,
  public.mk_price_snapshots, public.mk_sync_runs
from anon, authenticated;

grant select on
  public.mk_events, public.mk_markets, public.mk_outcomes, public.mk_price_snapshots
to anon, authenticated;

grant all on
  public.mk_events, public.mk_markets, public.mk_outcomes,
  public.mk_price_snapshots, public.mk_sync_runs
to service_role;

grant usage, select on sequences
  public.mk_events_id_seq,
  public.mk_markets_id_seq,
  public.mk_outcomes_id_seq,
  public.mk_price_snapshots_id_seq,
  public.mk_sync_runs_id_seq
to service_role;

commit;
